default:
  primary: yahoo
  fallback:
    - alpaca

exchanges:
  NASDAQ:
    primary: yahoo
    fallback:
      - alpaca
  NYSE:
    primary: yahoo
    fallback:
      - alpaca
  AMEX:
    primary: yahoo
    fallback:
      - alpaca
  CME:
    primary: yahoo
    fallback: []
  CBOE:
    primary: yahoo
    fallback: []
  CRYPTO:
    primary: crypto
    fallback:
      - yahoo
